source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'

gem 'sqlite3'
gem 'haml'
gem 'compass'
gem 'orm_adapter'
gem 'formtastic'
gem 'meta_search'
gem 'decent_exposure', '~> 1.0.0.rc1'
gem 'report_ui', :path => File.expand_path('../..', __FILE__)
group :development, :test, :cucumber do 
  gem 'ruby-debug19'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'nokogiri'
  gem 'capybara'
  gem 'capybara-webkit'
  gem 'webrat'
  gem 'machinist'
end
