source 'http://rubygems.org'

gem 'rails', '3.0.0'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'haml'
gem 'formtastic'
gem 'compass'
gem 'meta_search'
gem 'decent_exposure', '~> 1.0.0.rc1'

group :development, :test do 
  gem 'ruby-debug'
  gem 'rspec'
  gem 'rspec-rails'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'nokogiri'
  gem 'capybara'
  gem 'webrat'
  gem 'machinist'
end
