source 'http://rubygems.org'

gem 'rails', '3.1.0.rc4'
gem 'bundler', '~> 1.0.0'
gem 'orm_adapter'
gem 'jeweler', '~> 1.4.0'
gem 'haml'
gem 'compass'
gem 'formtastic'
gem 'meta_search'
gem 'decent_exposure', '~> 1.0.0.rc1'

group :development, :test do 
  gem 'rspec'
  gem 'rspec-core'
  gem 'rspec-expectations'
  gem 'rspec-mocks'
  gem 'rspec-rails'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'nokogiri'
  gem 'webrat'
  gem 'capybara'
  gem 'capybara-webkit', '1.0.0.beta4'
  gem 'ruby-debug19'
  gem 'machinist'
  gem 'sqlite3'
end
