# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{report_ui}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Bernardo Telles"]
  s.date = %q{2010-11-16}
  s.description = %q{Reporting engine for rails}
  s.email = %q{btelles@gmail.com}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".bundle/config",
     ".config/cucumber.yml",
     ".gitignore",
     ".gitkeep",
     "Gemfile",
     "Gemfile.lock",
     "MIT-LICENSE",
     "README",
     "Rakefile",
     "VERSION",
     "features/reports.feature",
     "features/step_definitions/bernie_steps.rb",
     "features/step_definitions/mislav_steps.rb",
     "features/step_definitions/web_steps.rb",
     "features/support/blueprints.rb",
     "features/support/env.rb",
     "features/support/models.rb",
     "features/support/paths.rb",
     "fixture_rails_root/.gitignore",
     "fixture_rails_root/Gemfile",
     "fixture_rails_root/Gemfile.lock",
     "fixture_rails_root/README",
     "fixture_rails_root/Rakefile",
     "fixture_rails_root/app/controllers/application_controller.rb",
     "fixture_rails_root/app/helpers/application_helper.rb",
     "fixture_rails_root/app/views/layouts/application.html.erb",
     "fixture_rails_root/config.ru",
     "fixture_rails_root/config/application.rb",
     "fixture_rails_root/config/boot.rb",
     "fixture_rails_root/config/database.yml",
     "fixture_rails_root/config/environment.rb",
     "fixture_rails_root/config/environments/development.rb",
     "fixture_rails_root/config/environments/production.rb",
     "fixture_rails_root/config/environments/test.rb",
     "fixture_rails_root/config/initializers/backtrace_silencers.rb",
     "fixture_rails_root/config/initializers/inflections.rb",
     "fixture_rails_root/config/initializers/mime_types.rb",
     "fixture_rails_root/config/initializers/report_ui.rb",
     "fixture_rails_root/config/initializers/secret_token.rb",
     "fixture_rails_root/config/initializers/session_store.rb",
     "fixture_rails_root/config/locales/en.yml",
     "fixture_rails_root/config/routes.rb",
     "fixture_rails_root/db/schema.rb",
     "fixture_rails_root/db/seeds.rb",
     "fixture_rails_root/doc/README_FOR_APP",
     "fixture_rails_root/lib/tasks/.gitkeep",
     "fixture_rails_root/public/404.html",
     "fixture_rails_root/public/422.html",
     "fixture_rails_root/public/500.html",
     "fixture_rails_root/public/favicon.ico",
     "fixture_rails_root/public/images/rails.png",
     "fixture_rails_root/public/index.html",
     "fixture_rails_root/public/javascripts/application.js",
     "fixture_rails_root/public/javascripts/controls.js",
     "fixture_rails_root/public/javascripts/dragdrop.js",
     "fixture_rails_root/public/javascripts/effects.js",
     "fixture_rails_root/public/javascripts/prototype.js",
     "fixture_rails_root/public/javascripts/rails.js",
     "fixture_rails_root/public/robots.txt",
     "fixture_rails_root/public/stylesheets/.gitkeep",
     "fixture_rails_root/script/rails",
     "fixture_rails_root/test/performance/browsing_test.rb",
     "fixture_rails_root/test/test_helper.rb",
     "generators/USAGE",
     "generators/report_ui_generator.rb",
     "init.rb",
     "install.rb",
     "lib/app/controllers/reports_controller.rb",
     "lib/app/models/report.rb",
     "lib/app/views/layouts/reports.html.haml",
     "lib/app/views/reports/_columns_editor.html.haml",
     "lib/app/views/reports/_details.html.haml",
     "lib/app/views/reports/_form.html.haml",
     "lib/app/views/reports/_report_details_edit.html.haml",
     "lib/app/views/reports/_reports_table.html.haml",
     "lib/app/views/reports/edit.html.haml",
     "lib/app/views/reports/index.html.haml",
     "lib/app/views/reports/new.html.haml",
     "lib/app/views/reports/show.html.haml",
     "lib/app/views/reports/show.js.erb",
     "lib/config/.routes.rb.swn",
     "lib/config/routes.rb",
     "public/javascripts/.gitkeep",
     "public/javascripts/application.js",
     "public/javascripts/jquery-ui.min.js",
     "public/javascripts/jquery.js",
     "public/javascripts/jrails.min.js",
     "public/stylesheets/.gitkeep",
     "public/stylesheets/formtastic.css",
     "public/stylesheets/formtastic_changes.css",
     "public/stylesheets/ie.css",
     "public/stylesheets/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "public/stylesheets/images/ui-bg_flat_55_fbec88_40x100.png",
     "public/stylesheets/images/ui-bg_glass_75_d0e5f5_1x400.png",
     "public/stylesheets/images/ui-bg_glass_85_dfeffc_1x400.png",
     "public/stylesheets/images/ui-bg_glass_95_fef1ec_1x400.png",
     "public/stylesheets/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png",
     "public/stylesheets/images/ui-bg_inset-hard_100_f5f8f9_1x100.png",
     "public/stylesheets/images/ui-bg_inset-hard_100_fcfdfd_1x100.png",
     "public/stylesheets/images/ui-icons_217bc0_256x240.png",
     "public/stylesheets/images/ui-icons_2e83ff_256x240.png",
     "public/stylesheets/images/ui-icons_469bdd_256x240.png",
     "public/stylesheets/images/ui-icons_6da8d5_256x240.png",
     "public/stylesheets/images/ui-icons_cd0a0a_256x240.png",
     "public/stylesheets/images/ui-icons_d8e7f3_256x240.png",
     "public/stylesheets/images/ui-icons_f9bd01_256x240.png",
     "public/stylesheets/jquery-ui.css",
     "public/stylesheets/print.css",
     "public/stylesheets/report_ui/formtastic.css",
     "public/stylesheets/report_ui/formtastic_changes.css",
     "public/stylesheets/report_ui/ie.css",
     "public/stylesheets/report_ui/images/ui-bg_flat_0_aaaaaa_40x100.png",
     "public/stylesheets/report_ui/images/ui-bg_flat_55_fbec88_40x100.png",
     "public/stylesheets/report_ui/images/ui-bg_glass_75_d0e5f5_1x400.png",
     "public/stylesheets/report_ui/images/ui-bg_glass_85_dfeffc_1x400.png",
     "public/stylesheets/report_ui/images/ui-bg_glass_95_fef1ec_1x400.png",
     "public/stylesheets/report_ui/images/ui-bg_gloss-wave_55_5c9ccc_500x100.png",
     "public/stylesheets/report_ui/images/ui-bg_inset-hard_100_f5f8f9_1x100.png",
     "public/stylesheets/report_ui/images/ui-bg_inset-hard_100_fcfdfd_1x100.png",
     "public/stylesheets/report_ui/images/ui-icons_217bc0_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_2e83ff_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_469bdd_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_6da8d5_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_cd0a0a_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_d8e7f3_256x240.png",
     "public/stylesheets/report_ui/images/ui-icons_f9bd01_256x240.png",
     "public/stylesheets/report_ui/jquery-ui.css",
     "public/stylesheets/report_ui/print.css",
     "public/stylesheets/report_ui/screen.css",
     "public/stylesheets/screen.css",
     "spec/controllers/reports_controller_spec.rb",
     "spec/lib/models_spec.rb",
     "spec/models/report_spec.rb",
     "spec/routing/routing_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/blueprints.rb",
     "spec/support/models.rb",
     "spec/views/reports/index.html.haml_spec.rb",
     "spec/views/reports/new.html.haml_spec.rb",
     "spec/views/reports/show.html.haml_spec.rb",
     "tasks/report_ui.rake",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/btelles/report_ui}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Reporting engine for Rails}
  s.test_files = [
    "spec/routing/routing_spec.rb",
     "spec/models/report_spec.rb",
     "spec/lib/models_spec.rb",
     "spec/controllers/reports_controller_spec.rb",
     "spec/support/blueprints.rb",
     "spec/support/models.rb",
     "spec/views/reports/show.html.haml_spec.rb",
     "spec/views/reports/new.html.haml_spec.rb",
     "spec/views/reports/index.html.haml_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["= 2.0.1"])
    else
      s.add_dependency(%q<rspec>, ["= 2.0.1"])
    end
  else
    s.add_dependency(%q<rspec>, ["= 2.0.1"])
  end
end

